apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: rabbit-cluster-dev
spec:
  serviceName: rabbit-cluster-dev
  replicas: 3
  template:
    metadata:
      labels:
        app: rabbit-cluster-dev
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
      - name: ost-logs
        emptyDir: {}
      - name: scratch-misc
        emptyDir: {}
      containers:
      - name: rabbit-cluster-dev
        image: cne-repos1.us.oracle.com:7744/apps/ugbu/odr/common/keep/odr-sandeep/odr-rmq:18.3a4
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 300m
            memory: 5120Mi
        ports:
          - name: queue-port
            containerPort: 5672
          - name: management-port
            containerPort: 15672
          - name: cluster-port
            containerPort: 4369
          - name: dist-port
            containerPort: 25672
        env:
          - name: RABBITMQ_USER
            value: guest
          - name: RABBITMQ_PASS
            value: "guest"
          - name: RABBITMQ_ERLANG_COOKIE
            value: "odrdatarakercookie"
          - name: RABBITMQ_USE_LONGNAME
            value: "true"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NODE_NAME
            value: "$(POD_NAME).rabbit-cluster-dev.odr-sandeep.svc.cluster.local"
          - name: RABBITMQ_NODENAME
            value: rabbit

#        livenessProbe:
#          exec:
#            command: ["/bin/sh", "-c", "/ugbu-server/temp/probe-script/rabbitLive.sh"]
#          initialDelaySeconds: 60
#          periodSeconds: 20
#          timeoutSeconds: 10
        readinessProbe:
          exec:
            command: ["true"]
           # - /bin/bash
          initialDelaySeconds: 60
          timeoutSeconds: 10
#          exec:
#            command: ["/bin/sh", "-c", "/ugbu-server/temp/probe-script/rabbitLive.sh"]
#          initialDelaySeconds: 60
#          periodSeconds: 20
#          timeoutSeconds: 10
#        command: ["/bin/sh", "-c", "/usr/sbin/rabbitmq-server"]

        volumeMounts:
        - name: scratch-misc
          mountPath: "/ugbu-server/temp"
        - name: rabbitmq
          mountPath: /var/lib/rabbitmq
          readOnly: false
        - name: ost-logs
          mountPath: /var/log/rabbitmq

      - name: rabbit-ost
        image: cne-repos1.us.oracle.com:7744/apps/ugbu/odr/common/keep/odr-sandeep/odr-rmq-ost:18.3
        imagePullPolicy: Always
        volumeMounts:
        - name: ost-logs
          mountPath: /ugbu-server/service/log/rabbitmq

      initContainers:
      - name: init-rabbit
        image: "cne-repos1.us.oracle.com:7744/apps/ugbu/odr/common/keep/odr-init-img:3.0"
        command: ["/bin/sh", "-c"]
        args:
          - wget http://rwsaa068.us.oracle.com/containers/CNE_Project/Docker_bin/odr-init/odr-sandeep/odr-probe-scripts.zip -P /tmp/;
            unzip /tmp/odr-probe-scripts.zip -d "/etc/misc/";
        volumeMounts:
        - name: scratch-misc
          mountPath: "/etc/misc"


  volumeClaimTemplates:
  - metadata:
      name: rabbitmq
      labels:
        name: rabbitmq-cluster-dev
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 30Gi
